name: Check File Encoding

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-encoding:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check UTF-8 Encoding
      run: |
        find . -type f \( -name "*.py" -o -name "*.md" -o -name "*.txt" \) -exec bash -c 'file -bi "$1" | grep -q "charset=utf-8" || echo "$1 is not UTF-8 encoded"' -- {} \;
        if [ $? -ne 0 ]; then
          exit 1
        fi