name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: |
        for file in $(find . -name '*.md'); do
          pandoc "$file" -o "${file%.md}.pdf"
        done
