name: test-windows
on: 
# push/ullrequest時にci実行
    push:
      branches: [master]
    pull_request:
        paths-ignore:
          - '.gitignore'
          - 'LICENSE'
          - '**.md'

# 環境変数
env:
  BRANCH_NAME : "master"

jobs:
  build:
    name: MSBuild
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10'] # [3.5, 3.6, 3.7, 3.8]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          path: target_dir
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
      - name: Set up virtual environment
        shell: powershell
        shell: powershell
        run: |
        run: python -m venv venv
          git --version
        run: .\venv\Scripts\Activate.ps1
          python --version
          python -m pip install --upgrade pip

      - name: tetris_sample
      # tetrisが動くかどうか確認(SCOREが入ればOK)
        shell: powershell
        working-directory: target_dir
        run: |
          # QT display off
          $Env:QT_QPA_PLATFORM = 'offscreen'
          # run tetris
          if( Test-Path .\requirements.txt ){ .\venv\Scripts\pip install -r requirements.txt }
          python start.py -m sample -t 3 -f $HOME/result.json

      - name: tetris_DQN_sample
        working-directory: target_dir
        shell: powershell
        run: |
          # QT display off
          $Env:QT_QPA_PLATFORM = 'offscreen'
          # run tetris
          if( Test-Path .\requirements.txt ){ .\venv\Scripts\pip install -r requirements.txt }
          if( Test-Path .\requirements.pytorch.txt ){ .\venv\Scripts\pip install -r requirements.pytorch.txt }
          python start.py -m predict_sample -l 2 -t 5 --predict_weight weight/DQN/sample_weight.pt -f $HOME/result_dqn.json

      - name: tetris_MLP_sample
        working-directory: target_dir
        shell: powershell
        run: |
          # QT display off
          $Env:QT_QPA_PLATFORM = 'offscreen'
          # run tetris
          if( Test-Path .\requirements.txt ){ .\venv\Scripts\pip install -r requirements.txt }
          if( Test-Path .\requirements.pytorch.txt ){ .\venv\Scripts\pip install -r requirements.pytorch.txt }
          python start.py -m predict_sample2 -l 2 -t 5 --predict_weight weight/MLP/sample_weight.pt -f $HOME/result_mlp.json

